#!/usr/bin/env bash

PIELABS="https://pielabs.github.io/pie-website"

mkdir pie-item  
cd pie-item
curl "$PIELABS/assets/demo-item/index.html" -o index.html
curl "$PIELABS/assets/demo-item/config.json" -o config.json 
