#!/usr/bin/env bash

which pie >/dev/null || { echo 'Please install the pie-cli project before continuing: https://github.com/pielabs/pie-cli' ; exit 1; }

root=$(pwd)

for dir in `ls content/assets/pies`;
do
  cd "$root/content/assets/pies/$dir"
  if [ ! -f "$root/content/assets/pies/$dir/pie-item.js" ]; then
    pie clean && pie pack -C --include-complete
  fi
done