#!/usr/bin/env bash

which pie >/dev/null || { echo 'Please install the pie-cli project before continuing: https://github.com/pielabs/pie-cli' ; exit 1; }

root=$(pwd)

for dir in `ls content/assets/pies`;
do
  echo "pack $dir"
  cd "$root/content/assets/pies/$dir"
  pie pack --clean --app website 
done